name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "Anuptestapp"
      ACR_NAME: "acrabf76d"
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login to Azure Container Registry
      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      # 4. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .

      # 5. Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

      # 6. Optional: Output image digest
      - name: Show Image Digest
        run: |
          az acr repository show-manifests --name $ACR_NAME --repository $IMAGE_NAME --query "[].digest"
